#ifndef REPLIES_HPP
# define REPLIES_HPP

# define RPL_AWAY				301
# define RPL_TOPIC				332
# define RPL_YOUREOPER			381
# define RPL_REHASHING			382
# define ERR_NOSUCHNICK			401
# define ERR_NOSUCHCHANNEL		403
# define ERR_CANNOTSENDTOCHAN	404
# define ERR_TOOMANYCHANNELS	405
# define ERR_TOOMANYTARGETS		407
# define ERR_NORECIPIENT		411
# define ERR_NOTEXTTOSEND		412
# define ERR_NOTOPLEVEL			413
# define ERR_WILDTOPLEVEL		414
# define ERR_UNKNOWNCOMMAND		421
# define ERR_NONICKNAMEGIVEN	431
# define ERR_ERRONEUSNICKNAME	432
# define ERR_NICKNAMEINUSE		433
# define ERR_NICKCOLLISION		436
# define ERR_UNAVAILRESOURCE	437
# define ERR_NEEDMOREPARAMS		461
# define ERR_ALREADYREGISTERED	462
# define ERR_PASSWDMISMATCH		464
# define ERR_CHANNELISFULL		471
# define ERR_INVITEONLYCHAN		473
# define ERR_BANNEDFROMCHAN		474
# define ERR_BADCHANNELKEY		475
# define ERR_BADCHANMASK		476
# define ERR_NOPRIVILEGES		481
# define ERR_CANTKILLSERVER		483
# define ERR_NOOPERHOST			491

#endif
